name: Build

# For each push on all branchs
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew shadowJar
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: ServerUtilsTest
        path: build/libs/ServerUtilsTest*.jar
